In [1]:
import tensorflow as tf

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
tf.__version__

'2.9.1'

In [4]:
dataset=pd.read_csv('Churn_Modelling.csv')
pd.set_option('display.expand_frame_repr', False)


In [5]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [6]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited
0             1    15634602   Hargrave          619    France  Female   42       2       0.00              1          1               1        101348.88       1
1             2    15647311       Hill          608     Spain  Female   41       1   83807.86              1          0               1        112542.58       0
2             3    15619304       Onio          502    France  Female   42       8  159660.80              3          1               0        113931.57       1
3             4    15701354       Boni          699    France  Female   39       1       0.00              2          0               0         93826.63       0
4             5    15737888   Mitchell          850     Spain  Female   43       2  125510.82              1          1               1         79084.10       0
...         ...         ...        ...          ...       ...     ...  ...     ...        ...            ...        ...             ...              ...     ...
9995       9996    15606229   Obijiaku          771    France    Male   39       5       0.00              2          1               0         96270.64       0
9996       9997    15569892  Johnstone          516    France    Male   35      10   57369.61              1          1               1        101699.77       0
9997       9998    15584532        Liu          709    France  Female   36       7       0.00              1          0               1         42085.58       1
9998       9999    15682355  Sabbatini          772   Germany    Male   42       3   75075.31              2          1               0         92888.52       1
9999      10000    15628319     Walker          792    France  Female   28       4  130142.79              1          1               0         38190.78       0

[10000 rows x 14 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [10]:
x[0:10]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [11]:
dataset['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoders',OneHotEncoder(),[1])],remainder='passthrough')

In [13]:
x=np.array(ct.fit_transform(x))

In [14]:
x[0:10]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [0.0, 1.0, 0.0, 376, 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [1.0, 0.0, 0.0, 501, 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [1.0, 0.0, 0.0, 684, 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=2)

## Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

## Building the ANN

### Initializing ANN

In [19]:
ann=tf.keras.models.Sequential()

### Addinf input layer and first hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding Second hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding Output layer

In [22]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training the ANN

In [23]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

## Training Ann on Training set

In [25]:
ann.fit(xtrain,ytrain,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 516us/step - loss: 0.3414 - accuracy: 0.8604
Epoch 2/100
250/250 [==============================] - 0s 519us/step - loss: 0.3410 - accuracy: 0.8599
Epoch 3/100
250/250 [==============================] - 0s 512us/step - loss: 0.3400 - accuracy: 0.8610
Epoch 4/100
250/250 [==============================] - 0s 517us/step - loss: 0.3399 - accuracy: 0.8619
Epoch 5/100
250/250 [==============================] - 0s 515us/step - loss: 0.3395 - accuracy: 0.8641
Epoch 6/100
250/250 [==============================] - 0s 512us/step - loss: 0.3390 - accuracy: 0.8611
Epoch 7/100
250/250 [==============================] - 0s 515us/step - loss: 0.3386 - accuracy: 0.8604
Epoch 8/100
250/250 [==============================] - 0s 519us/step - loss: 0.3393 - accuracy: 0.8612
Epoch 9/100
250/250 [==============================] - 0s 518us/step - loss: 0.3385 - accuracy: 0.8618
Epoch 10/100
250/250 [==============================] - 0s 516us/step - l

# Predicting

In [29]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 11ms/step
[[False]]


In [30]:
ypred=ann.predict(xtest)
ypred=(ypred>0.5)
print(np.concatenate((ypred.reshape(len(ypred),1),ytest.reshape(len(ytest),1)),1))

63/63 [==============================] - 0s 436us/step
[[0 1]
 [0 1]
 [1 1]
 ...
 [0 1]
 [0 1]
 [0 0]]


In [31]:
ypred

array([[False],
       [False],
       [ True],
       ...,
       [False],
       [False],
       [False]])

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(ytest,ypred)
print(cm)
accuracy_score(ytest,ypred)

[[1566   51]
 [ 234  149]]


0.8575